---
version: v3
name: "workstation_config"
services:
  rocky:
    build: .
    # command: ["/bin/bash"]
    # init: true
    tty: true
    privileged: true
    cgroup: host
    volumes:
      - ./:/ansible
      - /sys/fs/cgroup:/sys/fs/cgroup:rw