---
- name: Configure RPM System for development
  become: true
  hosts: localhost

  vars_prompt: 
    - name: primary_user
      prompt: "Enter username to create"

  pre_tasks:
    # - name: Set hostname
    #   ansible.builtin.hostname:
    #     name: "rockdock1"

    - name: Upgrade RHEL/CentOS Distribution
      dnf:
        name: "kernel"
        state: latest

    - name: Upgrade All Packages
      package:
        name: "*"
        state: latest
    
    - name: Create administrator user
      ansible.builtin.user:
        name: "{{ primary_user }}"
        shell: "{{ user_shell }}"
        groups: wheel
        append: yes
        state: present

  roles:
    - packages
    - config
    - gui
    - docker