---
- name: Configure RPM System for development
  become: true
  hosts: localhost

  pre_tasks:
    - name: Include Variables
      ansible.builtin.include_vars: vars/main.yml
      
    - name: Upgrade RHEL/CentOS Distribution
      ansible.builtin.dnf:
        name: "kernel"
        state: latest

    - name: Upgrade All Packages
      ansible.builtin.package:
        name: "*"
        state: latest

  roles:
    - packages
    - config
    - gui
    - docker