---
- name: Install Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - g++
    - openjdk-18-jdk
    - vim
    - traceroute
    - whois
    - python3.11
    - rust-all
    - wget
    - git
    - nmap
  
- name: Install Tauri Dev Dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - libwebkit2gtk-4.0-dev
    - build-essential
    - curl
    - wget
    - file
    - libssl-dev
    - libgtk3-dev
    - libayatana-appindicator3-dev
    - librsvg2-dev